"""add foreign keys and indexes

Revision ID: aea7622e74b4
Revises: 
Create Date: 2026-09-19 13:18:35.105843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea7622e74b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_pieces', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('mp3_file',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('cover',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_music_pieces_playlist_uuid'), ['playlist_uuid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_music_pieces_playlist_uuid_playlists'), 'playlists', ['playlist_uuid'], ['uuid'])

    with op.batch_alter_table('playlist_saved_by', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_playlist_saved_by_playlist_uuid'), ['playlist_uuid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_playlist_saved_by_playlist_uuid_playlists'), 'playlists', ['playlist_uuid'], ['uuid'])

    with op.batch_alter_table('playlist_shared_with', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_playlist_shared_with_playlist_uuid'), ['playlist_uuid'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_playlist_shared_with_playlist_uuid_playlists'), 'playlists', ['playlist_uuid'], ['uuid'])

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('owner',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('cover',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_playlists_owner'), ['owner'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_playlists_owner_users'), 'users', ['owner'], ['username'])

    with op.batch_alter_table('user_playlists_added_to', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('owner',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_user_playlists_added_to_username_users'), 'users', ['username'], ['username'])

    with op.batch_alter_table('user_saved_playlists', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('owner',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_user_saved_playlists_username_users'), 'users', ['username'], ['username'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('profile_picture',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('last_playback',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_playback',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_saved_playlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_saved_playlists_username_users'), type_='foreignkey')
        batch_op.alter_column('owner',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_playlists_added_to', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_playlists_added_to_username_users'), type_='foreignkey')
        batch_op.alter_column('owner',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlists_owner_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_playlists_owner'))
        batch_op.alter_column('cover',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('owner',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('playlist_shared_with', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlist_shared_with_playlist_uuid_playlists'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_playlist_shared_with_playlist_uuid'))
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('playlist_saved_by', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlist_saved_by_playlist_uuid_playlists'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_playlist_saved_by_playlist_uuid'))
        batch_op.alter_column('username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('music_pieces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_music_pieces_playlist_uuid_playlists'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_music_pieces_playlist_uuid'))
        batch_op.alter_column('artist',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cover',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mp3_file',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('playlist_uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('uuid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
